global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Your Go app (go-chi/metrics)
  - job_name: "go-clean-template"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8080"]
        labels:
          service: "go-clean-template"
          env: "local"
